spring:
  application:
    name: FilesPoc
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  datasource:
    url: jdbc:h2:mem:FilesPocdb
    username: surya
    password: surya
  h2:
    console:
      enabled: true  
      
      
      
      
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
   